services:
  airflow-scheduler:
    environment:
      - AIRFLOW_TEST_MODE=true
      - COLMAP_PATH=/usr/bin/colmap
    volumes:
      - ./data:/opt/airflow/data

  colmap:
    image: colmap/colmap:latest
    volumes:
      - ./data:/data
    environment:
      - DISPLAY=$DISPLAY
    profiles:
      - colmap
