version: '3.8'

services:
  test:
    image: python:3.7.9-slim
    volumes:
      - ./data:/app/data
      - ./src:/app/src
      - ./scripts:/app/scripts
      - ./requirements-reconstruction.txt:/app/requirements-reconstruction.txt
    environment:
      - PYTHONPATH=/app
      - PYTHONUNBUFFERED=1
      - DATA_DIR=/app/data
    command: >
      bash -c "
        echo '=== Testing E2E3D Reconstruction Pipeline ===' &&
        echo 'Python version:' &&
        python --version &&
        echo 'Setting up environment...' &&
        apt-get update &&
        apt-get install -y --no-install-recommends git wget unzip &&
        echo 'Installing Python packages...' &&
        pip install --no-cache-dir tqdm requests numpy pillow &&
        echo 'Checking for sample data...' &&
        if [ ! -d /app/data/input/CognacStJacquesDoor ]; then
          echo 'Sample data not found. Downloading sample data...' &&
          mkdir -p /app/data/input/CognacStJacquesDoor &&
          cd /app/scripts &&
          python download_sample_data.py CognacStJacquesDoor /app/data/input/CognacStJacquesDoor
        fi &&
        echo 'Running simple test to verify data access...' &&
        python -c 'import os; print(\"Found image files:\", len(os.listdir(\"/app/data/input/CognacStJacquesDoor\")))' &&
        echo 'Test completed successfully!'
      " 