version: '3'

services:
  minimal-test:
    image: python:3.7.9-slim
    container_name: e2e3d-minimal-test
    volumes:
      - ./data:/app/data
      - ./scripts:/app/scripts
    working_dir: /app
    command: >
      bash -c "
        echo 'Testing minimal E2E3D setup with Python 3.7.9'
        apt-get update && 
        apt-get install -y --no-install-recommends wget unzip git &&
        pip install tqdm requests numpy Pillow
        mkdir -p /app/data/input/CognacStJacquesDoor
        if [ ! -d /app/data/input/CognacStJacquesDoor ] || [ -z \"$(ls -A /app/data/input/CognacStJacquesDoor)\" ]; then
          echo 'Downloading sample data...'
          python /app/scripts/download_sample_data.py CognacStJacquesDoor /app/data/input
        fi
        echo 'Sample data check:'
        find /app/data/input/CognacStJacquesDoor -type f -name '*.jpg' -o -name '*.png' | wc -l
        echo 'Minimal test completed successfully!'
      " 