version: '3.8'

services:
  minio:
    image: minio/minio
    container_name: e2e3d-minio
    command: server /data --console-address ":9001"
    environment:
      - MINIO_ACCESS_KEY=minioadmin
      - MINIO_SECRET_KEY=minioadmin
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - minio-volume:/data
    networks:
      - e2e3d-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s
    
  minio-setup:
    image: minio/mc
    container_name: e2e3d-minio-setup
    depends_on:
      minio:
        condition: service_healthy
    entrypoint: >
      /bin/sh -c "
      /usr/bin/mc config host add myminio http://minio:9000 minioadmin minioadmin;
      /usr/bin/mc mb -p myminio/models;
      /usr/bin/mc anonymous set download myminio/models;
      exit 0;
      "
    networks:
      - e2e3d-network

networks:
  e2e3d-network:
    name: issues_e2e3d-network

volumes:
  minio-volume:
    name: issues_minio-volume
