version: '3.8'

services:
  minio:
    image: minio/minio:RELEASE.2023-07-21T21-12-44Z
    container_name: e2e3d-minio
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    volumes:
      - minio-volume:/data
    command: server /data --console-address ":9001"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 10s
      timeout: 5s
      retries: 3
    restart: always

  # Create MinIO buckets and set permissions
  minio-setup:
    image: minio/mc
    container_name: e2e3d-minio-setup
    depends_on:
      minio:
        condition: service_healthy
    entrypoint: >
      /bin/sh -c "
      /usr/bin/mc config host add myminio http://minio:9000 minioadmin minioadmin;
      /usr/bin/mc mb --ignore-existing myminio/models;
      /usr/bin/mc mb --ignore-existing myminio/input;
      /usr/bin/mc mb --ignore-existing myminio/output;
      /usr/bin/mc policy set download myminio/models;
      /usr/bin/mc policy set download myminio/output;
      exit 0;
      "
    restart: on-failure

volumes:
  minio-volume: 